import { MDRouter } from "../material/router/router.js";

MDRouter.historyApiFallback = false;

const routes = [
    {
        path: "",
        load: () => import("./main/main.js").then((m) => m.default),
        children: [
            /*  */{ path: "attribute-observer", load: () => import("./attribute-observer/attribute-observer").then((m) => m.default) },
            { path: "badge", load: () => import("./badge/badge").then((m) => m.default) },
            { path: "bottom-app-bar", load: () => import("./bottom-app-bar/bottom-app-bar").then((m) => m.default) },
            { path: "bottom-sheet", load: () => import("./bottom-sheet/bottom-sheet").then((m) => m.default) },
            { path: "button", load: () => import("./button/button").then((m) => m.default) },
            { path: "card", load: () => import("./card/card").then((m) => m.default) },
            { path: "checkbox", load: () => import("./checkbox/checkbox").then((m) => m.default) },
            /*  */{ path: "chip", load: () => import("./chip/chip").then((m) => m.default) },
            { path: "chips", load: () => import("./chips/chips").then((m) => m.default) },
            /*  */{ path: "color-field", load: () => import("./color-field/color-field").then((m) => m.default) },
            { path: "color-picker", load: () => import("./color-picker/color-picker").then((m) => m.default) },
            { path: "color", load: () => import("./color/color").then((m) => m.default) },
            /*  */{ path: "component", load: () => import("./component/component").then((m) => m.default) },
            /*  */{ path: "data-table-item", load: () => import("./data-table-item/data-table-item").then((m) => m.default) },
            { path: "data-table", load: () => import("./data-table/data-table").then((m) => m.default) },
            /*  */{ path: "date-field", load: () => import("./date-field/date-field").then((m) => m.default) },
            { path: "date-picker", load: () => import("./date-picker/date-picker").then((m) => m.default) },
            /*  */{ path: "datetime-field", load: () => import("./datetime-field/datetime-field").then((m) => m.default) },
            { path: "datetime-picker", load: () => import("./datetime-picker/datetime-picker").then((m) => m.default) },
            { path: "dialog", load: () => import("./dialog/dialog").then((m) => m.default) },
            { path: "emoji-picker", load: () => import("./emoji-picker/emoji-picker").then((m) => m.default) },
            { path: "emoji", load: () => import("./emoji/emoji").then((m) => m.default) },
            { path: "fab", load: () => import("./fab/fab").then((m) => m.default) },
            { path: "form", load: () => import("./form/form").then((m) => m.default) },
            /*  */{ path: "functions", load: () => import("./functions/functions").then((m) => m.default) },
            { path: "gesture", load: () => import("./gesture/gesture").then((m) => m.default) },
            { path: "icon-button", load: () => import("./icon-button/icon-button").then((m) => m.default) },
            { path: "icon", load: () => import("./icon/icon").then((m) => m.default) },
            { path: "image", load: () => import("./image/image").then((m) => m.default) },
            /*  */{ path: "list-item", load: () => import("./list-item/list-item").then((m) => m.default) },
            { path: "list", load: () => import("./list/list").then((m) => m.default) },
            { path: "localization", load: () => import("./localization/localization").then((m) => m.default) },
            { path: "markdown", load: () => import("./markdown/markdown").then((m) => m.default) },
            { path: "menu", load: () => import("./menu/menu").then((m) => m.default) },
            /*  */{ path: "month-field", load: () => import("./month-field/month-field").then((m) => m.default) },
            { path: "month-picker", load: () => import("./month-picker/month-picker").then((m) => m.default) },
            { path: "navigation-bar", load: () => import("./navigation-bar/navigation-bar").then((m) => m.default) },
            { path: "navigation-drawer", load: () => import("./navigation-drawer/navigation-drawer").then((m) => m.default) },
            { path: "navigation-rail", load: () => import("./navigation-rail/navigation-rail").then((m) => m.default) },
            /*  */{ path: "number-field", load: () => import("./number-field/number-field").then((m) => m.default) },
            /*  */{ path: "observer", load: () => import("./observer/observer").then((m) => m.default) },
            { path: "pagination", load: () => import("./pagination/pagination").then((m) => m.default) },
            /*  */{ path: "password-field", load: () => import("./password-field/password-field").then((m) => m.default) },
            { path: "popper", load: () => import("./popper/popper").then((m) => m.default) },
            { path: "progress-indicator", load: () => import("./progress-indicator/progress-indicator").then((m) => m.default) },
            /*  */{ path: "progress", load: () => import("./progress/progress").then((m) => m.default) },
            { path: "radio-button", load: () => import("./radio-button/radio-button").then((m) => m.default) },
            { path: "ripple", load: () => import("./ripple/ripple").then((m) => m.default) },
            /*  */{ path: "router", load: () => import("./router/router").then((m) => m.default) },
            // { path: "scrim", load: () => import("./scrim/scrim").then((m) => m.default) },
            /*  */{ path: "search-field", load: () => import("./search-field/search-field").then((m) => m.default) },
            { path: "segmented-button", load: () => import("./segmented-button/segmented-button").then((m) => m.default) },
            /*  */{ path: "select-field", load: () => import("./select-field/select-field").then((m) => m.default) },
            { path: "sheet", load: () => import("./sheet/sheet").then((m) => m.default) },
            { path: "side-sheet", load: () => import("./side-sheet/side-sheet").then((m) => m.default) },
            { path: "slider", load: () => import("./slider/slider").then((m) => m.default) },
            { path: "snackbar", load: () => import("./snackbar/snackbar").then((m) => m.default) },
            /*  */{ path: "store", load: () => import("./store/store").then((m) => m.default) },
            { path: "switch", load: () => import("./switch/switch").then((m) => m.default) },
            { path: "tabs", load: () => import("./tabs/tabs").then((m) => m.default) },
            { path: "text-field", load: () => import("./text-field/text-field").then((m) => m.default) },
            /*  */{ path: "textarea-field", load: () => import("./textarea-field/textarea-field").then((m) => m.default) },
            /*  */{ path: "time-field", load: () => import("./time-field/time-field").then((m) => m.default) },
            { path: "time-picker", load: () => import("./time-picker/time-picker").then((m) => m.default) },
            { path: "tooltip", load: () => import("./tooltip/tooltip").then((m) => m.default) },
            { path: "top-app-bar", load: () => import("./top-app-bar/top-app-bar").then((m) => m.default) },
            /*  */{ path: "tree-item", load: () => import("./tree-item/tree-item").then((m) => m.default) },
            { path: "tree", load: () => import("./tree/tree").then((m) => m.default) },
            { path: "virtual", load: () => import("./virtual/virtual").then((m) => m.default) },
            /*  */{ path: "week-field", load: () => import("./week-field/week-field").then((m) => m.default) },
            { path: "week-picker", load: () => import("./week-picker/week-picker").then((m) => m.default) },
        ],
    },
    { path: "*", load: () => import("./main/main.js").then((m) => m.default) },
];

MDRouter.init(routes);
