// import "./router/router.js";
// import "./base/controller.js";
// import "./base/component.js";
// import "./base/example-controller.js";
// import "./base/example-component.js";
// import "./ripple/ripple.js";
import "./layout/layout.js";
import "./icon/icon.js";
import "./emoji/emoji.js";
import "./image/image.js";
import "./bottom-app-bar/bottom-app-bar.js";
import "./top-app-bar/top-app-bar.js";
import "./badge/badge.js";
import "./button/button.js";
import "./fab/fab.js";
import "./icon-button/icon-button.js";
import "./segmented-button/segmented-button.js";
import "./card-header/card-header.js";
import "./card-body/card-body.js";
import "./card-footer/card-footer.js";
import "./card/card.js";
import "./carousel/carousel.js";
import "./checkbox/checkbox.js";
import "./chip/chip.js";
import "./chip-set/chip-set.js";
import "./date-picker/date-picker.js";
import "./dialog-header/dialog-header.js";
import "./dialog-body/dialog-body.js";
import "./dialog-footer/dialog-footer.js";
import "./dialog-scrim/dialog-scrim.js";
import "./dialog/dialog.js";
import "./divider/divider.js";
import "./list-item/list-item.js";
import "./list-row/list-row.js";
import "./list/list.js";
import "./menu/menu.js";
import "./navigation-bar/navigation-bar.js";
import "./navigation-drawer/navigation-drawer.js";
import "./navigation-rail/navigation-rail.js";
import "./progress-indicator/progress-indicator.js";
import "./radio-button/radio-button.js";
import "./search/search.js";
import "./sheet-header/sheet-header.js";
import "./sheet-body/sheet-body.js";
import "./sheet-footer/sheet-footer.js";
import "./sheet-scrim/sheet-scrim.js";
import "./sheet/sheet.js";
import "./bottom-sheet/bottom-sheet.js";
import "./side-sheet/side-sheet.js";
import "./slider/slider.js";
import "./snackbar/snackbar.js";
import "./switch/switch.js";
import "./tab/tab.js";
import "./text-field/text-field.js";
import "./time-picker/time-picker.js";
import "./tooltip/tooltip.js";